window.STUDYHUB_INTERVIEW = {
  topic: 'github',
  playground: 'playground.html',
  questions: [
    // ---------- Foundations ----------
    { id: 'gh-q1', level: 'easy', category: 'Foundations', type: 'concept',
      q: 'What is the difference between Git and GitHub?',
      answer: '<p><strong>Git</strong> is a distributed version-control <em>tool</em> that runs locally and needs no network. <strong>GitHub</strong> is a cloud service built around Git that hosts repositories and adds collaboration features: pull requests, issues, code review, Actions (CI/CD) and a social layer.</p><p>You can use Git with no GitHub account; GitHub is where teams collaborate on Git repos.</p>',
      source: { site: 'GitHub docs', label: 'What is GitHub?', url: 'https://docs.github.com/en/get-started/start-your-journey/what-is-github' } },
    { id: 'gh-q2', level: 'easy', category: 'Foundations', type: 'concept',
      q: 'What is a repository, and what does it contain beyond files?',
      answer: '<p>A repository hosts a project\'s files <em>and</em> its full Git history (commits, branches, tags), plus GitHub-only metadata: issues, pull requests, releases, settings, collaborators and Actions runs.</p><p>Cloning gives you the files and history; issues and PRs stay on GitHub.</p>',
      source: { site: 'GitHub docs', label: 'About repositories', url: 'https://docs.github.com/en/repositories/creating-and-managing-repositories/about-repositories' } },
    { id: 'gh-q3', level: 'easy', category: 'Foundations', type: 'concept',
      q: 'What are the three repository visibility levels?',
      answer: '<ul><li><strong>Public</strong> — anyone can read/clone (basis of open source).</li><li><strong>Private</strong> — only you and invited collaborators.</li><li><strong>Internal</strong> — all members of your organisation (Enterprise), hidden from the public.</li></ul><p>Pushing still requires explicitly granted write access regardless of visibility.</p>',
      source: { site: 'GitHub docs', label: 'About repositories', url: 'https://docs.github.com/en/repositories/creating-and-managing-repositories/about-repositories' } },
    { id: 'gh-q4', level: 'medium', category: 'Foundations', type: 'scenario',
      q: 'You made a private repo public. What is the security risk you must address first?',
      answer: '<p>Making a repo public exposes its <strong>entire history</strong>, not just the current files. A secret committed long ago and "deleted" in a later commit is still present in the history.</p><p><strong>Action:</strong> rotate/revoke any credential that was ever committed before going public — removing it from the working tree is not enough.</p>',
      source: { site: 'GitHub docs', label: 'About repositories', url: 'https://docs.github.com/en/repositories/creating-and-managing-repositories/about-repositories' } },

    // ---------- Account & auth ----------
    { id: 'gh-q5', level: 'easy', category: 'Account & Auth', type: 'concept',
      q: 'Why can you no longer use your account password for Git over HTTPS?',
      answer: '<p>Since 2021 GitHub removed password authentication for Git operations. Over HTTPS you authenticate with a <strong>Personal Access Token (PAT)</strong> in place of the password; over SSH you use a key pair. This reduces the damage of a leaked password and enables scoped, revocable credentials.</p>',
      source: { site: 'GitHub docs', label: 'Managing your personal access tokens', url: 'https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens' } },
    { id: 'gh-q6', level: 'medium', category: 'Account & Auth', type: 'concept',
      q: 'What makes a fine-grained PAT safer than a classic token?',
      answer: '<ul><li><strong>Repository scoping</strong> — grant access to specific repos only.</li><li><strong>Granular permissions</strong> — e.g. "Contents: read" + "Pull requests: write" and nothing else.</li><li><strong>Mandatory expiry</strong> — tokens die on their own, limiting a leak\'s window.</li></ul><p>Together these enforce least privilege; a classic token tends to carry broad scopes across everything you can see.</p>',
      source: { site: 'GitHub docs', label: 'Managing your personal access tokens', url: 'https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens' } },
    { id: 'gh-q7', level: 'easy', category: 'Account & Auth', type: 'coding',
      q: 'Generate an SSH key for GitHub and say which file you upload.',
      answer: '<pre>ssh-keygen -t ed25519 -C "you@example.com"\neval "$(ssh-agent -s)"\nssh-add ~/.ssh/id_ed25519\ncat ~/.ssh/id_ed25519.pub   # upload THIS one\nssh -T git@github.com</pre><p>You upload the <strong>public</strong> key (<code>id_ed25519.pub</code>). The private key (<code>id_ed25519</code>) never leaves your machine and is never shared.</p>',
      source: { site: 'GitHub docs', label: 'About SSH', url: 'https://docs.github.com/en/authentication/connecting-to-github-with-ssh/about-ssh' } },
    { id: 'gh-q8', level: 'easy', category: 'Account & Auth', type: 'concept',
      q: 'Why does GitHub require 2FA, and what should you save immediately after enabling it?',
      answer: '<p>2FA means a stolen password alone cannot log in — a second factor (authenticator app, passkey/security key, or SMS) is required. GitHub mandates it for contributors.</p><p>Immediately save your <strong>recovery codes</strong> offline; without them, losing your second factor can permanently lock you out.</p>',
      source: { site: 'GitHub docs', label: 'About two-factor authentication', url: 'https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/about-two-factor-authentication' } },

    // ---------- README / Markdown ----------
    { id: 'gh-q9', level: 'easy', category: 'README & Markdown', type: 'concept',
      q: 'What is special about a repo named exactly after your username?',
      answer: '<p>A repository whose name equals your username (e.g. <code>octocat/octocat</code>) is a <strong>profile repository</strong>: its <code>README.md</code> renders on your GitHub <em>profile</em> page, so it is used to introduce yourself.</p>',
      source: { site: 'GitHub docs', label: 'Basic writing and formatting syntax', url: 'https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax' } },
    { id: 'gh-q10', level: 'easy', category: 'README & Markdown', type: 'coding',
      q: 'Write GitHub-flavoured Markdown for a task list and a table.',
      answer: '<pre>- [x] done item\n- [ ] todo item\n\n| Name | Role |\n| ---- | ---- |\n| Ana  | Dev  |</pre><p>Task lists render as clickable checkboxes inside issues/PRs; ticking one updates the stored content live. Tables use pipes with a <code>---</code> separator row.</p>',
      source: { site: 'GitHub docs', label: 'Basic writing and formatting syntax', url: 'https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax' } },
    { id: 'gh-q11', level: 'medium', category: 'README & Markdown', type: 'scenario',
      q: 'Links in your README break on forks. What kind of links were you using?',
      answer: '<p>Absolute links (to a specific repo/branch URL) break when the repo is forked or renamed. Use <strong>relative</strong> links (<code>[Contributing](CONTRIBUTING.md)</code>) so they resolve against whatever repo/branch is currently being viewed.</p>',
      source: { site: 'GitHub docs', label: 'Basic writing and formatting syntax', url: 'https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax' } },

    // ---------- Forks ----------
    { id: 'gh-q12', level: 'easy', category: 'Forks', type: 'concept',
      q: 'What is the difference between a fork and a clone?',
      answer: '<p>A <strong>fork</strong> is a server-side copy of a repo under your own GitHub account. A <strong>clone</strong> is a copy on your local disk. The standard flow is: fork on GitHub, then clone <em>your fork</em> locally.</p>',
      source: { site: 'GitHub docs', label: 'About forks', url: 'https://docs.github.com/en/pull-requests/reference/forks' } },
    { id: 'gh-q13', level: 'medium', category: 'Forks', type: 'coding',
      q: 'How do you keep a fork in sync with the original project from the command line?',
      answer: '<pre>git remote add upstream https://github.com/orig/repo.git\ngit fetch upstream\ngit switch main\ngit merge upstream/main   # or: git rebase upstream/main\ngit push origin main</pre><p>Here <code>origin</code> is your fork (writable) and <code>upstream</code> is the original (read-only). The web UI\'s "Sync fork" button does the same.</p>',
      source: { site: 'GitHub docs', label: 'About forks', url: 'https://docs.github.com/en/pull-requests/reference/forks' } },
    { id: 'gh-q14', level: 'medium', category: 'Forks', type: 'scenario',
      q: 'You have no write access to a project but want to propose a change. What is the workflow?',
      answer: '<ol><li>Fork the repo.</li><li>Clone your fork, add <code>upstream</code>.</li><li>Create a feature branch and commit.</li><li><code>git push -u origin &lt;branch&gt;</code>.</li><li>Open a pull request from your fork\'s branch into the upstream repo.</li></ol><p>This "fork &amp; pull" model is how most open-source contributions happen.</p>',
      source: { site: 'GitHub docs', label: 'About forks', url: 'https://docs.github.com/en/pull-requests/reference/forks' } },

    // ---------- Issues ----------
    { id: 'gh-q15', level: 'easy', category: 'Issues', type: 'concept',
      q: 'What are labels, milestones and assignees on an issue?',
      answer: '<ul><li><strong>Labels</strong> — colour-coded categories (bug, enhancement, good first issue) for filtering.</li><li><strong>Milestone</strong> — a named target (e.g. "v2.0") with a progress bar across its issues/PRs.</li><li><strong>Assignee</strong> — who owns the work, so others don\'t duplicate it.</li></ul>',
      source: { site: 'GitHub docs', label: 'About issues', url: 'https://docs.github.com/en/issues/tracking-your-work-with-issues/learning-about-issues/about-issues' } },
    { id: 'gh-q16', level: 'medium', category: 'Issues', type: 'scenario',
      q: 'Why label a few tasks "good first issue"?',
      answer: '<p>GitHub surfaces repositories that use the <code>good first issue</code> label to newcomers looking to contribute. Tagging genuinely easy, well-scoped tasks is the single best way to attract first-time contributors to your project.</p>',
      source: { site: 'GitHub docs', label: 'About issues', url: 'https://docs.github.com/en/issues/tracking-your-work-with-issues/learning-about-issues/about-issues' } },
    { id: 'gh-q17', level: 'medium', category: 'Issues', type: 'concept',
      q: 'What exactly makes "Fixes #42" auto-close an issue?',
      answer: '<p>A closing keyword (<code>Fixes</code>/<code>Closes</code>/<code>Resolves</code>) followed by <code>#42</code> in a <strong>PR description</strong> or a commit message closes issue #42 — but only when the PR merges into the <strong>default branch</strong>. A plain comment saying "fixes #42" links but does not auto-close.</p>',
      source: { site: 'GitHub docs', label: 'About issues', url: 'https://docs.github.com/en/issues/tracking-your-work-with-issues/learning-about-issues/about-issues' } },

    // ---------- Pull requests ----------
    { id: 'gh-q18', level: 'easy', category: 'Pull Requests', type: 'concept',
      q: 'What is a pull request?',
      answer: '<p>A pull request proposes merging the commits on one branch into another. It is a <em>diff plus a conversation</em>: reviewers comment inline, CI runs automatically, and nothing lands until it meets the repo\'s merge requirements.</p>',
      source: { site: 'GitHub docs', label: 'Pull requests (reference)', url: 'https://docs.github.com/en/pull-requests/reference/pull-requests' } },
    { id: 'gh-q19', level: 'easy', category: 'Pull Requests', type: 'concept',
      q: 'What is a draft pull request for?',
      answer: '<p>A draft PR signals work-in-progress: it runs CI and is visible, but cannot be merged and does not send review-request notifications until marked "Ready for review". Use it for early CI feedback or to show direction without consuming reviewers\' time.</p>',
      source: { site: 'GitHub docs', label: 'Pull requests (reference)', url: 'https://docs.github.com/en/pull-requests/reference/pull-requests' } },
    { id: 'gh-q20', level: 'medium', category: 'Pull Requests', type: 'concept',
      q: 'What are the three outcomes of a review, and which blocks merge?',
      answer: '<ul><li><strong>Approve</strong> — safe to merge.</li><li><strong>Request changes</strong> — <em>blocks</em> merge until addressed (when required by protection).</li><li><strong>Comment</strong> — feedback with no verdict.</li></ul>',
      source: { site: 'GitHub docs', label: 'Pull requests (reference)', url: 'https://docs.github.com/en/pull-requests/reference/pull-requests' } },
    { id: 'gh-q21', level: 'medium', category: 'Pull Requests', type: 'coding',
      q: 'How does a reviewer propose an exact one-click code fix?',
      answer: '<p>Inside a line comment, a reviewer uses a suggestion block:</p><pre>```suggestion\nconst timeout = 5000;\n```</pre><p>The author applies it with one click (optionally batching several into one commit) — no local checkout needed. Ideal for typos and small tweaks.</p>',
      source: { site: 'GitHub docs', label: 'Pull requests (reference)', url: 'https://docs.github.com/en/pull-requests/reference/pull-requests' } },
    { id: 'gh-q22', level: 'medium', category: 'Pull Requests', type: 'coding',
      q: 'Open a draft PR, then mark it ready, using the gh CLI.',
      answer: '<pre>gh pr create --draft --title "WIP: auth" --body "early look"\n# later\ngh pr ready</pre><p><code>gh pr ready</code> flips the current PR from draft to ready, notifying requested reviewers.</p>',
      source: { site: 'GitHub CLI manual', label: 'gh pr create', url: 'https://cli.github.com/manual/gh_pr_create' } },

    // ---------- Code review ----------
    { id: 'gh-q23', level: 'medium', category: 'Code Review', type: 'scenario',
      q: 'Your PR is 2,000 lines and reviews are shallow. What should you change?',
      answer: '<p>Large PRs get rubber-stamped; small ones get careful review. Split the work into smaller, logically-scoped PRs (ideally one logical change each — don\'t mix a refactor with a feature). Self-review your own diff first, and make CI green before requesting human review.</p>',
      source: { site: 'GitHub docs', label: 'Pull requests (reference)', url: 'https://docs.github.com/en/pull-requests/reference/pull-requests' } },
    { id: 'gh-q24', level: 'easy', category: 'Code Review', type: 'concept',
      q: 'What does "require conversation resolution" do?',
      answer: '<p>It is a branch-protection option that blocks merge until <strong>every review comment thread is marked resolved</strong>, so a reviewer\'s comment cannot be quietly ignored before the PR lands.</p>',
      source: { site: 'GitHub docs', label: 'About protected branches', url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches' } },

    // ---------- Branch protection / CODEOWNERS ----------
    { id: 'gh-q25', level: 'medium', category: 'Branch Protection', type: 'concept',
      q: 'Name four things a branch-protection rule on main can require.',
      answer: '<ul><li>Require a pull request before merging (no direct pushes).</li><li>Require N approving reviews.</li><li>Require status checks (named CI) to pass.</li><li>Require the branch be up to date; dismiss stale approvals; block force-pushes/deletions; require signed commits or linear history.</li></ul>',
      source: { site: 'GitHub docs', label: 'About protected branches', url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches' } },
    { id: 'gh-q26', level: 'hard', category: 'Branch Protection', type: 'concept',
      q: 'How do rulesets improve on classic branch-protection rules?',
      answer: '<ul><li><strong>Layered</strong> — multiple rulesets combine on one branch rather than one winning.</li><li><strong>Target branches and tags</strong> by fnmatch pattern (e.g. <code>release/*</code>).</li><li><strong>Evaluate mode</strong> — report-only, to see what would be blocked before enforcing.</li><li><strong>Org-level</strong> and explicit, audited <strong>bypass lists</strong>.</li></ul>',
      source: { site: 'GitHub docs', label: 'About protected branches', url: 'https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches' } },
    { id: 'gh-q27', level: 'medium', category: 'Branch Protection', type: 'coding',
      q: 'In a CODEOWNERS file, which rule applies when several patterns match a file?',
      answer: '<p>The <strong>last matching line</strong> wins. Example:</p><pre>*                 @org/maintainers\n/src/payments/    @org/finance-team\n*.tf              @org/infra</pre><p>A change to <code>/src/payments/x.tf</code> is owned by <code>@org/infra</code> (the last match), so order your most specific rules carefully.</p>',
      source: { site: 'GitHub docs', label: 'About code owners', url: 'https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners' } },
    { id: 'gh-q28', level: 'easy', category: 'Branch Protection', type: 'concept',
      q: 'What does a CODEOWNERS file do?',
      answer: '<p>It maps file-path patterns to the users/teams who own them. When a PR touches a matching path, GitHub <strong>auto-requests</strong> those owners\' review, and with "Require review from Code Owners" their approval becomes mandatory.</p>',
      source: { site: 'GitHub docs', label: 'About code owners', url: 'https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners' } },

    // ---------- Merge strategies ----------
    { id: 'gh-q29', level: 'medium', category: 'Merge Strategies', type: 'concept',
      q: 'Contrast merge, squash and rebase merges in terms of main\'s history.',
      answer: '<table><thead><tr><th>Strategy</th><th>Result on main</th></tr></thead><tbody><tr><td>Merge commit</td><td>All PR commits kept + one merge commit (non-linear)</td></tr><tr><td>Squash</td><td>One new commit per PR; linear; individual commits lost on main</td></tr><tr><td>Rebase</td><td>Each commit replayed with new SHAs; linear; no merge commit</td></tr></tbody></table>',
      source: { site: 'GitHub docs', label: 'About pull request merges', url: 'https://docs.github.com/en/pull-requests/reference/pull-request-merges' } },
    { id: 'gh-q30', level: 'medium', category: 'Merge Strategies', type: 'scenario',
      q: 'You want a tidy main where every commit is one complete feature. Which strategy?',
      answer: '<p><strong>Squash and merge.</strong> It collapses a PR\'s "wip / fix typo / oops" commits into one clean commit on main, giving a bisect-friendly, one-commit-per-feature history. The trade-off is losing the per-step authorship on main (still visible inside the PR).</p>',
      source: { site: 'GitHub docs', label: 'About pull request merges', url: 'https://docs.github.com/en/pull-requests/reference/pull-request-merges' } },
    { id: 'gh-q31', level: 'hard', category: 'Merge Strategies', type: 'concept',
      q: 'Why do commit SHAs change with a rebase merge, and why is that normally safe for a PR?',
      answer: '<p>A commit\'s SHA is a hash of its content <em>and its parent</em>. Rebasing replays each commit onto a new parent (the latest base), so every replayed commit gets a new SHA. It is safe when merging a PR because the feature branch\'s commits were not relied upon elsewhere; avoid rebasing commits others have already pulled.</p>',
      source: { site: 'GitHub docs', label: 'About pull request merges', url: 'https://docs.github.com/en/pull-requests/reference/pull-request-merges' } },

    // ---------- Actions basics ----------
    { id: 'gh-q32', level: 'easy', category: 'Actions', type: 'concept',
      q: 'Define event, workflow, job, step and runner.',
      answer: '<ul><li><strong>Event</strong> — what triggers a run (push, pull_request, schedule).</li><li><strong>Workflow</strong> — a YAML file in <code>.github/workflows/</code> reacting to events.</li><li><strong>Job</strong> — a unit of work on its own fresh runner.</li><li><strong>Step</strong> — one action (<code>uses:</code>) or shell command (<code>run:</code>).</li><li><strong>Runner</strong> — the VM/container that executes a job.</li></ul>',
      source: { site: 'GitHub docs', label: 'Understand GitHub Actions', url: 'https://docs.github.com/en/actions/get-started/understand-github-actions' } },
    { id: 'gh-q33', level: 'easy', category: 'Actions', type: 'concept',
      q: 'Where must workflow files live, and what is the difference between "uses" and "run"?',
      answer: '<p>Workflow files must be in <code>.github/workflows/*.yml</code> at the repo root. In a step, <code>uses:</code> invokes a reusable action (e.g. <code>actions/checkout@v4</code>); <code>run:</code> executes a raw shell command.</p>',
      source: { site: 'GitHub docs', label: 'Workflow syntax', url: 'https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax' } },
    { id: 'gh-q34', level: 'medium', category: 'Actions', type: 'coding',
      q: 'Write a minimal CI workflow that runs tests on every pull request to main.',
      answer: '<pre>name: CI\non:\n  pull_request:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: \'20\'\n      - run: npm ci\n      - run: npm test</pre>',
      source: { site: 'GitHub docs', label: 'Workflow syntax', url: 'https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax' } },

    // ---------- Actions in depth ----------
    { id: 'gh-q35', level: 'medium', category: 'Actions In Depth', type: 'coding',
      q: 'Write a matrix that tests three Node versions on three operating systems.',
      answer: '<pre>strategy:\n  fail-fast: false\n  matrix:\n    os: [ubuntu-latest, windows-latest, macos-latest]\n    node: [18, 20, 22]\nruns-on: ${{ matrix.os }}</pre><p>This expands to 3 × 3 = 9 parallel jobs. <code>fail-fast: false</code> lets the rest finish if one fails.</p>',
      source: { site: 'GitHub docs', label: 'Run job variations (matrix)', url: 'https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations' } },
    { id: 'gh-q36', level: 'medium', category: 'Actions In Depth', type: 'concept',
      q: 'When do you use caching vs artifacts?',
      answer: '<p><strong>Cache</strong> (<code>actions/cache</code>) speeds up re-runs by restoring dependencies keyed on a lockfile hash. <strong>Artifacts</strong> (<code>upload/download-artifact</code>) move <em>output</em> files (binaries, reports) between jobs or to a human. Cache = inputs you can rebuild; artifacts = outputs you produced.</p>',
      source: { site: 'GitHub docs', label: 'Workflow syntax', url: 'https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax' } },
    { id: 'gh-q37', level: 'medium', category: 'Actions In Depth', type: 'concept',
      q: 'How do Actions secrets and variables differ?',
      answer: '<p>Both are referenced in YAML (<code>${{ secrets.X }}</code> / <code>${{ vars.X }}</code>) and scoped at repo/environment/org level. The key difference: <strong>secrets are masked in logs</strong>; variables are shown in plain text. Use secrets for tokens/keys, variables for non-sensitive config. Never <code>echo</code> a secret.</p>',
      source: { site: 'GitHub docs', label: 'Use secrets in Actions', url: 'https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-secrets' } },
    { id: 'gh-q38', level: 'hard', category: 'Actions In Depth', type: 'scenario',
      q: 'A deploy job must wait for a human to approve before it runs. How?',
      answer: '<p>Attach the job to a protected <strong>environment</strong> with required reviewers:</p><pre>jobs:\n  deploy:\n    environment:\n      name: production\n    steps:\n      - run: ./deploy.sh</pre><p>On reaching the job the run pauses until a named reviewer approves. Environments can also hold a wait timer and environment-scoped secrets.</p>',
      source: { site: 'GitHub docs', label: 'Control deployments', url: 'https://docs.github.com/en/actions/how-tos/deploy/configure-and-manage-deployments/control-deployments' } },
    { id: 'gh-q39', level: 'hard', category: 'Actions In Depth', type: 'concept',
      q: 'Why set an explicit permissions block for GITHUB_TOKEN?',
      answer: '<p>The automatic <code>GITHUB_TOKEN</code> can be broader than a job needs. Declaring <code>permissions:</code> with the minimum scopes (e.g. <code>contents: read</code>) enforces least privilege, so a compromised step or dependency can do far less damage. Grant write scopes (<code>contents: write</code>, <code>packages: write</code>, <code>id-token: write</code>) only where required.</p>',
      source: { site: 'GitHub docs', label: 'Workflow syntax', url: 'https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax' } },
    { id: 'gh-q40', level: 'hard', category: 'Actions In Depth', type: 'concept',
      q: 'What does OIDC (id-token: write) let a deploy job avoid?',
      answer: '<p>OpenID Connect lets a workflow prove its identity to a cloud provider and receive a <strong>short-lived</strong> credential at run time, so you never store a long-lived cloud key as a secret. The job needs <code>id-token: write</code> and a trust policy configured on the cloud side.</p>',
      source: { site: 'GitHub docs', label: 'Use secrets in Actions', url: 'https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/use-secrets' } },
    { id: 'gh-q41', level: 'medium', category: 'Actions In Depth', type: 'coding',
      q: 'How do you stop two rapid pushes from running overlapping deploys?',
      answer: '<pre>concurrency:\n  group: deploy-${{ github.ref }}\n  cancel-in-progress: true</pre><p>Runs in the same group are serialised; <code>cancel-in-progress: true</code> cancels the older in-flight run so the newest push wins.</p>',
      source: { site: 'GitHub docs', label: 'Workflow syntax', url: 'https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax' } },

    // ---------- Deploy / Pages ----------
    { id: 'gh-q42', level: 'medium', category: 'Deploy & Pages', type: 'coding',
      q: 'What permissions does a GitHub Pages deploy workflow need, and why two jobs?',
      answer: '<p>It needs <code>pages: write</code> and <code>id-token: write</code> (plus <code>contents: read</code>). It uses two jobs: a <strong>build</strong> job that produces the site and uploads it with <code>upload-pages-artifact</code>, and a <strong>deploy</strong> job (<code>needs: build</code>) that publishes it with <code>deploy-pages</code>, gated by the <code>github-pages</code> environment.</p>',
      source: { site: 'GitHub docs', label: 'Control deployments', url: 'https://docs.github.com/en/actions/how-tos/deploy/configure-and-manage-deployments/control-deployments' } },
    { id: 'gh-q43', level: 'easy', category: 'Deploy & Pages', type: 'concept',
      q: 'What can GitHub Pages NOT do?',
      answer: '<p>Pages serves <strong>static</strong> files only (HTML/CSS/JS/images) over HTTPS. It cannot run server-side code, databases or back-end logic — only client-side JavaScript. For dynamic needs you deploy elsewhere.</p>',
      source: { site: 'GitHub docs', label: 'What is GitHub Pages?', url: 'https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages' } },
    { id: 'gh-q44', level: 'medium', category: 'Deploy & Pages', type: 'scenario',
      q: 'Your framework\'s _next assets 404 on Pages. What is the fix?',
      answer: '<p>Pages runs Jekyll by default, which ignores files/folders starting with an underscore. Add an empty <code>.nojekyll</code> file at the site root to disable Jekyll processing so <code>_next</code>/<code>_app</code> are served as-is.</p>',
      source: { site: 'GitHub docs', label: 'What is GitHub Pages?', url: 'https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages' } },

    // ---------- Packages / releases ----------
    { id: 'gh-q45', level: 'medium', category: 'Packages & Releases', type: 'coding',
      q: 'Push a Docker image to GHCR from an Actions workflow without a PAT.',
      answer: '<pre>permissions:\n  contents: read\n  packages: write\nsteps:\n  - uses: docker/login-action@v3\n    with:\n      registry: ghcr.io\n      username: ${{ github.actor }}\n      password: ${{ secrets.GITHUB_TOKEN }}\n  - uses: docker/build-push-action@v6\n    with:\n      push: true\n      tags: ghcr.io/${{ github.repository }}:latest</pre>',
      source: { site: 'GitHub docs', label: 'Working with the Container registry', url: 'https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry' } },
    { id: 'gh-q46', level: 'easy', category: 'Packages & Releases', type: 'concept',
      q: 'How do a tag and a release differ?',
      answer: '<p>A <strong>tag</strong> is a Git label on a commit (e.g. <code>v1.2.0</code>). A <strong>release</strong> is a GitHub object built on a tag that adds release notes and downloadable assets and a Releases-page entry. Every release points at one tag; not every tag has a release.</p>',
      source: { site: 'GitHub docs', label: 'About releases', url: 'https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases' } },
    { id: 'gh-q47', level: 'medium', category: 'Packages & Releases', type: 'coding',
      q: 'Create a release with auto-generated notes using the gh CLI.',
      answer: '<pre>git tag -a v1.2.0 -m "Release 1.2.0"\ngit push origin v1.2.0\ngh release create v1.2.0 --generate-notes ./dist/app.zip</pre><p><code>--generate-notes</code> builds the changelog from merged PRs since the last release; the trailing path attaches a downloadable asset.</p>',
      source: { site: 'GitHub docs', label: 'About releases', url: 'https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases' } },

    // ---------- Security ----------
    { id: 'gh-q48', level: 'medium', category: 'Security', type: 'concept',
      q: 'What is the difference between Dependabot alerts and security updates?',
      answer: '<p><strong>Alerts</strong> notify you when a dependency you use has a known vulnerability. <strong>Security updates</strong> go further and automatically open a PR bumping that dependency to a fixed version. Separately, <strong>version updates</strong> keep dependencies current on a schedule via <code>dependabot.yml</code>.</p>',
      source: { site: 'GitHub docs', label: 'About GitHub Advanced Security', url: 'https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security' } },
    { id: 'gh-q49', level: 'medium', category: 'Security', type: 'concept',
      q: 'What does secret-scanning push protection do that plain secret scanning does not?',
      answer: '<p>Plain secret scanning <em>detects</em> a committed credential and alerts you after the fact. <strong>Push protection</strong> blocks the push <em>before</em> the secret enters history (with a logged override path), stopping the leak at the source.</p>',
      source: { site: 'GitHub docs', label: 'About GitHub Advanced Security', url: 'https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security' } },
    { id: 'gh-q50', level: 'hard', category: 'Security', type: 'scenario',
      q: 'Secret scanning flags a leaked AWS key already in history. What is your FIRST action and why?',
      answer: '<p><strong>Rotate/revoke the credential immediately.</strong> Treat it as already compromised — public pushes are scraped within seconds and the value may be cached. Rewriting history to remove the key does <em>not</em> undo exposure; it only prevents future reads of a value an attacker may already hold.</p>',
      source: { site: 'GitHub docs', label: 'About GitHub Advanced Security', url: 'https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security' } },
    { id: 'gh-q51', level: 'easy', category: 'Security', type: 'concept',
      q: 'What is code scanning / CodeQL, and how is it different from Dependabot?',
      answer: '<p>Code scanning runs static analysis on <em>your own source</em> to find vulnerabilities (SQL injection, path traversal). GitHub\'s engine, <strong>CodeQL</strong>, treats code as a queryable database. Dependabot covers <em>dependencies</em>; CodeQL covers the code you wrote. Results appear in the Security tab and inline on PRs; external tools upload in SARIF format.</p>',
      source: { site: 'GitHub docs', label: 'About GitHub Advanced Security', url: 'https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security' } },

    // ---------- gh CLI / Codespaces / Licenses ----------
    { id: 'gh-q52', level: 'medium', category: 'gh CLI', type: 'coding',
      q: 'Merge PR #42 with squash and delete its branch, then check out PR #7 locally.',
      answer: '<pre>gh pr merge 42 --squash --delete-branch\ngh pr checkout 7</pre><p><code>gh pr checkout</code> fetches the PR\'s branch and switches to it, so you can run it locally and review in a real environment.</p>',
      source: { site: 'GitHub CLI manual', label: 'gh pr merge', url: 'https://cli.github.com/manual/gh_pr_merge' } },
    { id: 'gh-q53', level: 'easy', category: 'Codespaces', type: 'concept',
      q: 'What is a Codespace and what defines its environment?',
      answer: '<p>A Codespace is a cloud-hosted dev environment (a container reached via VS Code) with your repo already cloned and tools installed. Its environment is defined by <code>.devcontainer/devcontainer.json</code> — the base image, features, extensions, forwarded ports and setup commands — so everyone gets an identical, reproducible setup.</p>',
      source: { site: 'GitHub docs', label: 'What are Codespaces?', url: 'https://docs.github.com/en/codespaces/about-codespaces/what-are-codespaces' } },
    { id: 'gh-q54', level: 'medium', category: 'Open Source', type: 'scenario',
      q: 'A public repo has no LICENSE file. Can others legally reuse the code?',
      answer: '<p>No. With no license, the code is "all rights reserved" by default — being public grants visibility, not reuse rights. To let people use/modify/distribute it you must add a license (MIT and Apache 2.0 are common permissive choices; GPL/AGPL are copyleft/share-alike).</p>',
      source: { site: 'GitHub docs', label: 'Licensing a repository', url: 'https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository' } }
  ]
};
